### ISSUE TITLE
Is the  way of parameters sharing  written exactly right？

### ISSUE THREAD

**Issue by liaolin** [hengruo/QANet-pytorch#4]
Is the  way of parameters sharing  written exactly right？

**Comment by hengruo** [comment]
@liaolin I wrote them by my comprehension. If you have any suggestions, please let me know.

**Comment by InitialBug** [comment]
I use the same encoder block in the model layer to compute the M0,M1,M2 instead of three blocks, and that's my way of sharing weights of the three blocks. But in the embedding layer, the length of question and paragraph is different, so I think if we want to do the weight sharing job, we must decompose the block or pass the weight to the block in the __init__ method

**Comment by hengruo** [comment]
@InitialBug You're right. The paper said, "We also share weights of the context and question encoder, and of the three output encoders." Thanks a lot!
